"""
Pine Script v5 code generator.

Converts a Python strategy class into a self-contained Pine Script v5
strategy file ready to paste into TradingView.
"""

import json
import textwrap
from datetime import datetime


def generate(strategy_class, output_path: str = None) -> str:
    """
    Generate Pine Script v5 code from a strategy class.

    The strategy class must have:
        - name: str
        - version: str
        - params: dict
        - pine_script() -> str  (returns Pine Script logic)

    Returns the full Pine Script code as a string.
    """
    name = getattr(strategy_class, "name", "unnamed_strategy")
    version = getattr(strategy_class, "version", "1.0")
    params = getattr(strategy_class, "params", {})
    description = getattr(strategy_class, "description", "")

    # Get strategy-specific Pine Script logic
    if hasattr(strategy_class, "pine_script"):
        if callable(strategy_class.pine_script):
            logic = strategy_class.pine_script()
        else:
            logic = strategy_class.pine_script
    else:
        logic = "// TODO: Implement strategy logic"

    # Build the full script
    pine = _build_pine_script(
        name=name,
        version=version,
        params=params,
        description=description,
        logic=logic,
    )

    if output_path:
        with open(output_path, "w") as f:
            f.write(pine)
        print(f"  Pine Script exported to: {output_path}")

    return pine


def _build_pine_script(name: str, version: str, params: dict,
                       description: str, logic: str) -> str:
    """Assemble the complete Pine Script v5 file."""

    # Generate input declarations from params
    inputs = _generate_inputs(params)

    now = datetime.now().strftime("%Y-%m-%d %H:%M")

    script = f"""//@version=5
// ══════════════════════════════════════════════════════════════════════
// Strategy: {name} v{version}
// Generated by Signal Pilot Strategy Lab
// Date: {now}
// {description}
// ══════════════════════════════════════════════════════════════════════

strategy("{name} v{version}", overlay=true, default_qty_type=strategy.percent_of_equity,
     default_qty_value=1, commission_type=strategy.commission.percent,
     commission_value=0.01, slippage=2, initial_capital=10000,
     process_orders_on_close=false, calc_on_every_tick=false)

// ─── Inputs ─────────────────────────────────────────────────────────
{inputs}

// ─── Strategy Logic ─────────────────────────────────────────────────
{logic}
"""
    return script


def _generate_inputs(params: dict) -> str:
    """Convert params dict to Pine Script input declarations."""
    lines = []
    for key, value in params.items():
        label = key.replace("_", " ").title()
        pine_key = key

        if isinstance(value, bool):
            lines.append(f'{pine_key} = input.bool({str(value).lower()}, "{label}")')
        elif isinstance(value, int):
            lines.append(f'{pine_key} = input.int({value}, "{label}")')
        elif isinstance(value, float):
            step = _infer_step(value)
            lines.append(f'{pine_key} = input.float({value}, "{label}", step={step})')
        elif isinstance(value, str):
            lines.append(f'{pine_key} = input.string("{value}", "{label}")')

    return "\n".join(lines)


def _infer_step(value: float) -> float:
    """Infer a reasonable step size for a float input."""
    if value >= 10:
        return 1.0
    elif value >= 1:
        return 0.1
    else:
        return 0.01


# ─── Pine Script Templates ──────────────────────────────────────────────

TREND_FOLLOWING_TEMPLATE = """
// ─── Indicator Calculations ─────────────────────────────────────────
fast_ma = ta.ema(close, fast_ema)
slow_ma = ta.ema(close, slow_ema)
atr_val = ta.atr(atr_period)
rsi_val = ta.rsi(close, rsi_period)

// ─── Trend Filter ───────────────────────────────────────────────────
trend_up = fast_ma > slow_ma
trend_down = fast_ma < slow_ma

// ─── Entry Conditions ───────────────────────────────────────────────
long_entry = ta.crossover(fast_ma, slow_ma) and rsi_val < rsi_ob
short_entry = ta.crossunder(fast_ma, slow_ma) and rsi_val > rsi_os

// ─── Stop Loss & Take Profit ────────────────────────────────────────
long_sl = close - atr_val * atr_sl_mult
long_tp = close + atr_val * atr_tp_mult
short_sl = close + atr_val * atr_sl_mult
short_tp = close - atr_val * atr_tp_mult

// ─── Execute Trades ─────────────────────────────────────────────────
if long_entry
    strategy.entry("Long", strategy.long)
    strategy.exit("Long Exit", "Long", stop=long_sl, limit=long_tp)

if short_entry
    strategy.entry("Short", strategy.short)
    strategy.exit("Short Exit", "Short", stop=short_sl, limit=short_tp)

// ─── Plots ──────────────────────────────────────────────────────────
plot(fast_ma, "Fast EMA", color=color.new(color.blue, 0), linewidth=2)
plot(slow_ma, "Slow EMA", color=color.new(color.orange, 0), linewidth=2)

bgcolor(trend_up ? color.new(color.green, 95) : trend_down ? color.new(color.red, 95) : na)
"""

MEAN_REVERSION_TEMPLATE = """
// ─── Indicator Calculations ─────────────────────────────────────────
[bb_upper, bb_mid, bb_lower] = ta.bb(close, bb_period, bb_std)
rsi_val = ta.rsi(close, rsi_period)
atr_val = ta.atr(atr_period)

// ─── Entry Conditions ───────────────────────────────────────────────
long_entry = close < bb_lower and rsi_val < rsi_os
short_entry = close > bb_upper and rsi_val > rsi_ob

// ─── Stop Loss & Take Profit ────────────────────────────────────────
long_sl = close - atr_val * atr_sl_mult
long_tp = bb_mid
short_sl = close + atr_val * atr_sl_mult
short_tp = bb_mid

// ─── Execute Trades ─────────────────────────────────────────────────
if long_entry
    strategy.entry("Long", strategy.long)
    strategy.exit("Long Exit", "Long", stop=long_sl, limit=long_tp)

if short_entry
    strategy.entry("Short", strategy.short)
    strategy.exit("Short Exit", "Short", stop=short_sl, limit=short_tp)

// ─── Plots ──────────────────────────────────────────────────────────
plot(bb_upper, "BB Upper", color=color.gray)
plot(bb_mid, "BB Mid", color=color.yellow)
plot(bb_lower, "BB Lower", color=color.gray)
fill(plot(bb_upper), plot(bb_lower), color=color.new(color.blue, 92))
"""
