# -*- coding: utf-8 -*-
"""Build education/assets/chatbot-i18n-<lang>.js from the per-language sources.

    python3 scripts/curriculum/chatbot_i18n.py            rebuild the file
    python3 scripts/curriculum/chatbot_i18n.py --check    exit 1 if it is stale

The widget picks an answer by matching typed words against keyword lists, so a
localisation is three tables and not one: the answers, the interface strings,
and the words that reach each answer in that language. They live in
scripts/i18n/chatbot/<lang>.json and are assembled here, so nobody has to
hand-edit a large JavaScript literal and no language can be half-written into
it.

English is the fallback for every key, so a language that is missing an answer
shows the English one rather than an empty bubble.
"""
import os, re, sys, json, glob, collections

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
os.chdir(ROOT)
sys.path.insert(0, os.path.join(ROOT, 'scripts/i18n'))
sys.path.insert(0, os.path.join(ROOT, 'scripts/i18n/checks'))
from chatbot_refs import expand
import numerals as numcheck
SRC = 'scripts/i18n/chatbot'
OUT = 'education/assets/chatbot-i18n-%s.js'
CAT = json.load(open('education/curriculum/index.json', encoding='utf-8'))
TIER = collections.Counter(r['level'] for r in CAT)
SLOT = {r['order']: r for r in CAT}

HEAD = """/* Translations for the education chatbot, %s. Generated by
 * scripts/curriculum/chatbot_i18n.py from scripts/i18n/chatbot/<lang>.json --
 * do not edit this file by hand.
 *
 * One file per language, and chatbot.js fetches only the reader's own. A
 * single bundle carrying all twelve was half a megabyte on every page in the
 * site, and a German reader downloaded eleven tables they would never see.
 * The English answers and keyword list live in chatbot.js itself, so only
 * ui.en is carried here as the fallback for a missing interface string.
 *
 * chatbot.js reads the reader's language off <html lang> and looks each string
 * up here, falling back to English key by key. `keys` holds the words that
 * should reach each answer in that language: the English regexes in chatbot.js
 * never fire for someone typing German, so without these a translated widget
 * would answer every question with the fallback.
 *
 * `enOnly` is the list, per language, of the /education/ paths an answer links
 * to that do not exist in that reader's tree. Everything else is rewritten to
 * their own prefix at render time, so a German reader following a lesson link
 * lands on the German lesson. The list is computed from disk on every build,
 * so a page translated later drops off it and its links start pointing home.
 */
"""


def load(lang):
    p = os.path.join(SRC, lang + '.json')
    return json.load(open(p, encoding='utf-8')) if os.path.exists(p) else None


def check_english(en):
    """The answers quote tier sizes. Hold them to the catalogue."""
    bad = []
    for key, text in en['kb'].items():
        for m in re.finditer(r'\*\*Tier \d: (\w+)\*\* \((\d+) lessons?\)', text):
            tier, n = m.group(1), int(m.group(2))
            if TIER.get(tier) != n:
                bad.append('%s: says %s has %d lessons, catalogue has %d'
                           % (key, tier, n, TIER.get(tier)))
        for m in re.finditer(r'\*\*Weeks [^*]*: (\w+)\*\* \((\d+) lessons?, slots (\d+)-(\d+)\)',
                             text):
            tier, n, lo, hi = m.group(1), int(m.group(2)), int(m.group(3)), int(m.group(4))
            if TIER.get(tier) != n:
                bad.append('%s: says %s has %d lessons, catalogue has %d'
                           % (key, tier, n, TIER.get(tier)))
            if hi - lo + 1 != TIER.get(tier, 0):
                bad.append('%s: %s slots %d-%d span %d, catalogue has %d'
                           % (key, tier, lo, hi, hi - lo + 1, TIER.get(tier)))
    total = len(CAT)
    for key, text in en['kb'].items():
        for m in re.finditer(r'in order, 1 to (\d+)', text):
            if int(m.group(1)) != total:
                bad.append('%s: recommends 1 to %s, the course has %d lessons'
                           % (key, m.group(1), total))
        for m in re.finditer(r'\*\*Total:\*\* (\d+) ', text):
            if int(m.group(1)) != total:
                bad.append('%s: totals %s lessons, catalogue has %d'
                           % (key, m.group(1), total))
    # A bare "(Lesson 5)" is a citation too, and the one that rotted: the help
    # answer listed RSI at lesson 5, the spread at 21 and automation at 57,
    # all of them slots from the pre-renumber course.
    for key, text in en['kb'].items():
        for m in re.finditer(r'\((?:Lesson|lesson) (\d+)\)', text):
            if int(m.group(1)) not in SLOT:
                bad.append('%s: cites lesson %s, which does not exist'
                           % (key, m.group(1)))
        for n, t in re.findall(r'\[Lesson (\d+): ([^\]]+)\]', text):
            r = SLOT.get(int(n))
            if r is None:
                bad.append('%s: links lesson %s, which does not exist' % (key, n))
            elif r['title'] != t:
                bad.append('%s: calls lesson %s %r, the catalogue calls it %r'
                           % (key, n, t, r['title']))
    for key, text in en['kb'].items():
        for u in re.findall(r'\]\((/education/[^)]*)\)', text):
            if not os.path.exists('.' + u):
                bad.append('%s: dead link %s' % (key, u))
    return bad


LANGS = ['de', 'es', 'fr', 'it', 'pt', 'nl', 'ru', 'ja', 'tr', 'hu', 'ar']


def en_only(tables):
    """Per language, the linked /education/ paths that tree does not have.

    A link is rewritten into the reader's own tree unless it is on this list,
    which is exactly the pages that exist in English and nowhere else. Computed
    rather than typed, because the set shrinks as pages get translated and a
    typed list would go stale silently and send readers to a 404.
    """
    urls = set()
    for kb in tables:
        for text in kb.values():
            urls |= set(re.findall(r'\]\((/education/[^)]*)\)', text))
    out = {}
    for lang in LANGS:
        miss = sorted(u for u in urls
                      if not os.path.exists(lang + (u + 'index.html' if u.endswith('/') else u)))
        if miss:
            out[lang] = miss
    return out


def figures(text, lang=None):
    """The measurements in one answer, with every locale's separators removed.

    Deliberately stricter than checks/numerals.py, which also accepts a figure
    written to less precision because a lesson may legitimately round. An
    answer here quotes the lesson's own number, so 9.84 and 9.64 must not
    compare equal -- and under the looser rule they do, because both carry the
    form "9". Only the flattened token counts: English 18,952 and German
    18.952 are one figure, and 9.64 is not 9.84.
    """
    text = numcheck.ENT.sub(' ', text)
    if lang == 'ja':
        text = numcheck._ja_myriad(text)
    out = collections.Counter()
    for m in numcheck.NUM.finditer(text):
        tok = m.group(0)
        if numcheck.measured(tok):
            out[re.sub('[.,\u00a0\u202f ]', '', tok)] += 1
    return out


def check_locale(lang, en_kb, kb):
    """Every figure in an English answer must survive into its translation.

    The answers are almost entirely measurements, and the one defect a reader
    of translated prose cannot catch is a figure that drifted: 9.84 typed as
    9.64, a 253 that became 235.
    """
    bad = []
    for key, text in sorted(kb.items()):
        if key not in en_kb:
            bad.append('%s: %s is not an English answer' % (lang, key))
            continue
        want, got = figures(en_kb[key]), figures(text, lang)
        miss = want - got
        if miss:
            bad.append('%s %s: missing %s'
                       % (lang, key, sorted(miss.elements())))
    return bad


QUICK = {'quickStartQuery': 'start', 'quickBeginnerQuery': 'beginner',
         'quickRsiQuery': 'rsi', 'quickAutomationQuery': 'automation'}


def route(keys, text):
    """Which answer a typed question reaches, replaying the widget's own rule.

    chatbot.js builds one case-insensitive alternation per key and takes the
    first hit in insertion order, so the order of the table is part of the
    localisation and not decoration.
    """
    for key, words in keys.items():
        if not words:
            continue
        alt = '|'.join(re.escape(w) for w in words)
        if re.search('(' + alt + ')', text, re.I):
            return key
    return None


def check_keys(lang, en_keys, d):
    """The trigger table must keep the English order, and the four buttons
    must still reach the answers they are labelled with."""
    bad = []
    keys = d.get('keys', {})
    if list(keys) != list(en_keys):
        extra = [k for k in keys if k not in en_keys]
        short = [k for k in en_keys if k not in keys]
        if extra:
            bad.append('%s: keys has %s, which English does not' % (lang, extra))
        if short:
            bad.append('%s: keys is missing %s' % (lang, short))
        if not extra and not short:
            bad.append('%s: keys are in a different order from English; the '
                       'widget takes the first hit, so the order is the '
                       'routing' % lang)
    ui = d.get('ui', {})
    for field, want in QUICK.items():
        q = ui.get(field)
        if not q:
            continue
        got = route(keys, q)
        if got != want:
            bad.append('%s: the %s button types %r, which reaches %s, not %s'
                       % (lang, field, q, got, want))
    return bad


def build():
    en = load('en')
    if en is None:
        raise SystemExit('%s/en.json is the source of truth and is missing' % SRC)
    bad = check_english(en)
    if bad:
        for b in bad:
            print('  ' + b)
        raise SystemExit('%d English findings; fix them before building' % len(bad))

    langs, ui, keys = [], {'en': en['ui']}, {'en': en['keys']}
    kb = {'en': {k: expand('en', v) for k, v in en['kb'].items()}}
    for p in sorted(glob.glob(os.path.join(SRC, '*.json'))):
        lang = os.path.basename(p)[:-5]
        if lang == 'en':
            continue
        d = json.load(open(p, encoding='utf-8'))
        langs.append(lang)
        ui[lang] = d.get('ui', {})
        # A translated answer cites lessons as {L69} and gets the locale's own
        # title, word for "Lesson" and href spliced in here, so an answer can
        # never disagree with the page it links to.
        kb[lang] = {k: expand(lang, v) for k, v in d.get('kb', {}).items()}
        keys[lang] = d.get('keys', {})
        bad.extend(check_locale(lang, kb['en'], kb[lang]))
        bad.extend(check_keys(lang, en['keys'], d))
    if bad:
        for b in bad:
            print('  ' + b)
        raise SystemExit('%d findings; fix them before building' % len(bad))

    j = lambda o: json.dumps(o, ensure_ascii=False, indent=2)
    only = en_only(kb.values())
    files = {}
    for lang in ['en'] + langs:
        # English answers and keywords are already inside chatbot.js, so a file
        # carries only what that reader adds to them. ui.en is the exception:
        # it is the fallback for every interface string, English included.
        u = {'en': ui['en']} if lang == 'en' else {'en': ui['en'], lang: ui[lang]}
        k = {} if lang == 'en' else {lang: kb[lang]}
        y = {} if lang == 'en' else {lang: keys[lang]}
        o = {} if lang == 'en' else {lang: only[lang]} if lang in only else {}
        files[lang] = (HEAD % lang + 'window.SP_CHATBOT_I18N = {\n'
                       '  languages: %s,\n  enOnly: %s,\n  ui: %s,\n  kb: %s,\n  keys: %s\n};\n'
                       % (json.dumps(['en'] + langs), j(o), j(u), j(k), j(y)))
    return files, langs


def main(argv):
    files, langs = build()
    stale = []
    for lang, out in sorted(files.items()):
        p = OUT % lang
        cur = open(p, encoding='utf-8').read() if os.path.exists(p) else ''
        if out != cur:
            stale.append((p, out))
    # The one-file-for-everything bundle every page used to load.
    old = 'education/assets/chatbot-i18n.js'
    if not stale and not os.path.exists(old):
        print('%d language files current' % len(files))
        return 0
    if '--check' in argv:
        for p, _ in stale:
            print('%s is stale' % p)
        if os.path.exists(old):
            print('%s is the old single bundle and should be gone' % old)
        return 1
    for p, out in stale:
        open(p, 'w', encoding='utf-8').write(out)
    if os.path.exists(old):
        os.remove(old)
        print('removed %s' % old)
    print('%d of %d language files rewritten (%s)'
          % (len(stale), len(files), ', '.join(langs)))
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
