# -*- coding: utf-8 -*-
"""Build education/assets/chatbot-i18n.js from the per-language sources.

    python3 scripts/curriculum/chatbot_i18n.py            rebuild the file
    python3 scripts/curriculum/chatbot_i18n.py --check    exit 1 if it is stale

The widget picks an answer by matching typed words against keyword lists, so a
localisation is three tables and not one: the answers, the interface strings,
and the words that reach each answer in that language. They live in
scripts/i18n/chatbot/<lang>.json and are assembled here, so nobody has to
hand-edit a large JavaScript literal and no language can be half-written into
it.

English is the fallback for every key, so a language that is missing an answer
shows the English one rather than an empty bubble.
"""
import os, re, sys, json, glob, collections

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
os.chdir(ROOT)
SRC = 'scripts/i18n/chatbot'
OUT = 'education/assets/chatbot-i18n.js'
CAT = json.load(open('education/curriculum/index.json', encoding='utf-8'))
TIER = collections.Counter(r['level'] for r in CAT)
SLOT = {r['order']: r for r in CAT}

HEAD = """/* Translations for the education chatbot. Generated by
 * scripts/curriculum/chatbot_i18n.py from scripts/i18n/chatbot/<lang>.json --
 * do not edit this file by hand.
 *
 * chatbot.js reads the reader's language off <html lang> and looks each string
 * up here, falling back to English key by key. `keys` holds the words that
 * should reach each answer in that language: the English regexes in chatbot.js
 * never fire for someone typing German, so without these a translated widget
 * would answer every question with the fallback.
 */
"""


def load(lang):
    p = os.path.join(SRC, lang + '.json')
    return json.load(open(p, encoding='utf-8')) if os.path.exists(p) else None


def check_english(en):
    """The answers quote tier sizes. Hold them to the catalogue."""
    bad = []
    for key, text in en['kb'].items():
        for m in re.finditer(r'\*\*Tier \d: (\w+)\*\* \((\d+) lessons?\)', text):
            tier, n = m.group(1), int(m.group(2))
            if TIER.get(tier) != n:
                bad.append('%s: says %s has %d lessons, catalogue has %d'
                           % (key, tier, n, TIER.get(tier)))
        for m in re.finditer(r'\*\*Weeks [^*]*: (\w+)\*\* \((\d+) lessons?, slots (\d+)-(\d+)\)',
                             text):
            tier, n, lo, hi = m.group(1), int(m.group(2)), int(m.group(3)), int(m.group(4))
            if TIER.get(tier) != n:
                bad.append('%s: says %s has %d lessons, catalogue has %d'
                           % (key, tier, n, TIER.get(tier)))
            if hi - lo + 1 != TIER.get(tier, 0):
                bad.append('%s: %s slots %d-%d span %d, catalogue has %d'
                           % (key, tier, lo, hi, hi - lo + 1, TIER.get(tier)))
    total = len(CAT)
    for key, text in en['kb'].items():
        for m in re.finditer(r'in order, 1 to (\d+)', text):
            if int(m.group(1)) != total:
                bad.append('%s: recommends 1 to %s, the course has %d lessons'
                           % (key, m.group(1), total))
        for m in re.finditer(r'\*\*Total:\*\* (\d+) ', text):
            if int(m.group(1)) != total:
                bad.append('%s: totals %s lessons, catalogue has %d'
                           % (key, m.group(1), total))
    # A bare "(Lesson 5)" is a citation too, and the one that rotted: the help
    # answer listed RSI at lesson 5, the spread at 21 and automation at 57,
    # all of them slots from the pre-renumber course.
    for key, text in en['kb'].items():
        for m in re.finditer(r'\((?:Lesson|lesson) (\d+)\)', text):
            if int(m.group(1)) not in SLOT:
                bad.append('%s: cites lesson %s, which does not exist'
                           % (key, m.group(1)))
        for n, t in re.findall(r'\[Lesson (\d+): ([^\]]+)\]', text):
            r = SLOT.get(int(n))
            if r is None:
                bad.append('%s: links lesson %s, which does not exist' % (key, n))
            elif r['title'] != t:
                bad.append('%s: calls lesson %s %r, the catalogue calls it %r'
                           % (key, n, t, r['title']))
    for key, text in en['kb'].items():
        for u in re.findall(r'\]\((/education/[^)]*)\)', text):
            if not os.path.exists('.' + u):
                bad.append('%s: dead link %s' % (key, u))
    return bad


def build():
    en = load('en')
    if en is None:
        raise SystemExit('%s/en.json is the source of truth and is missing' % SRC)
    bad = check_english(en)
    if bad:
        for b in bad:
            print('  ' + b)
        raise SystemExit('%d English findings; fix them before building' % len(bad))

    langs, ui, kb, keys = [], {'en': en['ui']}, {'en': en['kb']}, {'en': en['keys']}
    for p in sorted(glob.glob(os.path.join(SRC, '*.json'))):
        lang = os.path.basename(p)[:-5]
        if lang == 'en':
            continue
        d = json.load(open(p, encoding='utf-8'))
        langs.append(lang)
        ui[lang] = d.get('ui', {})
        kb[lang] = d.get('kb', {})
        keys[lang] = d.get('keys', {})

    j = lambda o: json.dumps(o, ensure_ascii=False, indent=2)
    return (HEAD + 'window.SP_CHATBOT_I18N = {\n'
            '  languages: %s,\n  ui: %s,\n  kb: %s,\n  keys: %s\n};\n'
            % (json.dumps(langs), j(ui), j(kb), j(keys))), langs


def main(argv):
    out, langs = build()
    cur = open(OUT, encoding='utf-8').read() if os.path.exists(OUT) else ''
    if out == cur:
        print('%s current: English plus %d languages' % (OUT, len(langs)))
        return 0
    if '--check' in argv:
        print('%s is stale' % OUT)
        return 1
    open(OUT, 'w', encoding='utf-8').write(out)
    print('%s rebuilt: English plus %d languages%s'
          % (OUT, len(langs), (' (' + ', '.join(langs) + ')') if langs else ''))
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
